const PHONE = "995555320865";
const WHATSAPP_LINK = "https://wa.me/message/3XB2AJBAQTQMK1";

const translations = {
  ru: {
    meta_title: "BoxMove - грузоперевозки в Тбилиси и Грузии",
    meta_description: "BoxMove: грузоперевозки, переезды, грузовое такси и грузчики в Тбилиси и по всей Грузии. Быстро, аккуратно, 24/7.",
    skip_link: "К услугам", nav_services: "Услуги", nav_about: "О нас", nav_prices: "Форматы", nav_reviews: "Отзывы", nav_faq: "FAQ",
    hero_eyebrow: "Грузоперевозки в Тбилиси и по всей Грузии", hero_title: "BoxMove - аккуратно перевезем вещи, мебель и крупные грузы", hero_text: "Подаем чистый фургон, подбираем грузчиков, бережно упаковываем и доставляем без лишнего стресса. Работаем с квартирами, офисами, магазинами и стройками.", hero_primary: "Рассчитать в WhatsApp", hero_secondary: "Наши услуги", hero_proof_1: "Подача от 40 минут", hero_proof_2: "Грузчики по запросу", hero_proof_3: "Безопасная упаковка",
    status_today: "Сегодня", status_from: "от", status_city: "Тбилиси + вся Грузия",
    strip_1_title: "Аккуратная работа", strip_1_text: "Бережно относимся к мебели, технике и личным вещам.", strip_2_title: "Вместительный фургон", strip_2_text: "Подходит для переезда, доставки и грузового такси.", strip_3_title: "Маршруты по Грузии", strip_3_text: "Тбилиси, Батуми, Кутаиси, Рустави и другие города.",
    services_eyebrow: "Что перевозим", services_title: "Услуги BoxMove", services_text: "Можно заказать только машину, машину с грузчиками, вывоз мусора или переезд под ключ с упаковкой, разборкой и сборкой мебели.", service_1_title: "Перевозка мебели и техники", service_1_text: "Диваны, шкафы, холодильники, стиральные машины и крупные предметы.", service_2_title: "Доставка стройматериалов", service_2_text: "Песок, цемент, плитка, доски и материалы с доставкой на объект.", service_3_title: "Грузовое такси по Тбилиси", service_3_text: "Быстрая подача машины для коробок, покупок, оборудования и товаров.", service_4_title: "Офисные переезды", service_4_text: "Перевезем столы, кресла, документы, технику и торговое оборудование.", service_5_title: "Грузчики и упаковка", service_5_text: "Подъем на этаж, спуск, пленка, картон, защита углов и аккуратная погрузка.", service_6_title: "Межгород по Грузии", service_6_text: "Доставим груз между городами с понятной ценой и временем прибытия.", service_7_title: "Сборка и разборка мебели", service_7_text: "Разберем шкаф, кровать или стол перед перевозкой и соберем на новом месте.", service_8_title: "Вывоз мусора", service_8_text: "Вывезем строительный мусор, старую мебель и ненужные вещи после ремонта или переезда.", service_9_title: "Переезд под ключ", service_9_text: "Привезем коробки и пленку, упакуем вещи, разберем мебель, перевезем и соберем на новом месте.", service_cta: "Рассчитать",
    about_eyebrow: "Почему BoxMove", about_title: "Переезд должен быть спокойным, а не хаосом", about_text: "Мы заранее уточняем объем, этаж, лифт, хрупкие вещи и маршрут. Приезжаем вовремя, закрепляем груз в кузове и держим связь до завершения заказа.", about_stat_1: "средняя оценка клиентов", about_stat_2: "перевозок за сезон", about_stat_3: "средняя подача по городу", fleet_badge: "Фургон для города и трассы", fleet_title: "Mercedes Sprinter / аналог", fleet_text: "Чистый кузов, ремни крепления, пледы и место для крупной мебели.",
    prices_eyebrow: "Прозрачный расчет", prices_title: "Популярные форматы", prices_text: "Каждый заказ собираем под задачу: маршрут, объем, этаж, грузчики, упаковка и ожидание. Быстрый расчет можно получить в WhatsApp.", price_1_label: "Грузовое такси", price_1_value: "Городская подача", price_1_text: "Когда нужно быстро перевезти вещи по Тбилиси", price_1_item_1: "Фургон с водителем", price_1_item_2: "До 1 часа работы", price_1_item_3: "Подача по району", price_2_label: "Переезд с грузчиками", price_2_value: "Переезд с командой", price_2_text: "Для квартиры, офиса или магазина", price_2_item_1: "Фургон + 2 грузчика", price_2_item_2: "Погрузка и выгрузка", price_2_item_3: "Бережное крепление груза", price_3_label: "Межгород", price_3_value: "Маршрут по Грузии", price_3_text: "Тбилиси - Батуми, Кутаиси, Рустави и другие города", price_3_item_1: "Точное время выезда", price_3_item_2: "Фото груза перед отправкой", price_3_item_3: "Связь в пути",
    quote_eyebrow: "Быстрый расчет", quote_title: "Опишите перевозку - мы сразу ответим", quote_text: "Форма открывает готовое сообщение в WhatsApp. Добавьте адреса, тип груза и количество грузчиков.", estimate_label: "Ориентир:", estimate_note: "Точная цена после уточнения деталей", form_from: "Откуда", form_to: "Куда", form_type: "Тип услуги", form_helpers: "Грузчики", form_comment: "Что нужно перевезти", form_from_placeholder: "Сабуртало, Тбилиси", form_to_placeholder: "Ваке, Тбилиси", form_comment_placeholder: "Например: диван, холодильник, 12 коробок", form_type_taxi: "Грузовое такси", form_type_move: "Переезд", form_type_turnkey: "Переезд под ключ", form_type_materials: "Стройматериалы", form_type_junk: "Вывоз мусора", form_type_intercity: "Межгород", form_helpers_0: "Не нужны", form_helpers_1: "1 грузчик", form_helpers_2: "2 грузчика", form_helpers_3: "3+ грузчика", form_submit: "Отправить в WhatsApp",
    reviews_eyebrow: "Отзывы", reviews_title: "Клиенты ценят скорость и аккуратность", review_1_text: "\"Ребята приехали вовремя, разобрали шкаф, все аккуратно подняли на 5 этаж. Цена была как договорились.\"", review_1_name: "Анна", review_1_meta: "Переезд Ваке - Сабуртало", review_2_text: "\"Нужно было быстро доставить плитку и цемент на объект. Машина приехала через час, помогли выгрузить.\"", review_2_name: "Гиорги", review_2_meta: "Стройматериалы по Тбилиси", review_3_text: "\"Заказывали офисный переезд вечером. Все коробки доехали целыми, техника была закреплена.\"", review_3_name: "Мария", review_3_meta: "Офисный переезд",
    faq_eyebrow: "FAQ", faq_title: "Частые вопросы", faq_1_q: "Можно заказать машину сегодня?", faq_1_a: "Да, если есть свободный слот. По Тбилиси часто можем подать фургон в течение 40-90 минут.", faq_2_q: "Вы работаете без лифта?", faq_2_a: "Да. Мы заранее уточняем этаж и количество вещей, чтобы поставить нужное число грузчиков и назвать честную цену.", faq_3_q: "Можно перевезти груз в другой город?", faq_3_a: "Да, перевозим по всей Грузии. Цена зависит от расстояния, веса, объема и срочности.", faq_4_q: "Есть упаковка?", faq_4_a: "Можем привезти пленку, картон, скотч и защитные материалы. Сложную мебель можно разобрать и собрать.",
    contacts_eyebrow: "Контакты", contacts_title: "Напишите BoxMove - подберем машину и время", contacts_text: "Лучше всего отправить фото вещей, адреса и желаемое время. Мы быстро скажем цену и свободный слот.", contacts_call: "Позвонить", contacts_whatsapp: "WhatsApp", contacts_telegram: "Telegram", contacts_phone_label: "Телефон", contacts_area_label: "Зона", contacts_area: "Тбилиси и вся Грузия", contacts_hours_label: "Время", contacts_hours: "Ежедневно 07:00-23:00, срочные заказы 24/7", footer_text: "Грузоперевозки, переезды и грузовое такси в Тбилиси и по Грузии.", mobile_cta: "WhatsApp расчет", whatsapp_message: "Здравствуйте, хочу рассчитать перевозку BoxMove."
  },
  en: {
    meta_title: "BoxMove - moving and cargo transport in Tbilisi, Georgia", meta_description: "BoxMove provides moving, cargo taxi, loaders and delivery services in Tbilisi and across Georgia. Fast, careful, 24/7.", skip_link: "Skip to services", nav_services: "Services", nav_about: "About", nav_prices: "Formats", nav_reviews: "Reviews", nav_faq: "FAQ",
    hero_eyebrow: "Cargo transport in Tbilisi and across Georgia", hero_title: "BoxMove moves furniture, boxes and bulky cargo with care", hero_text: "We provide a clean van, loaders on request, careful packing and delivery without stress. We work with apartments, offices, shops and construction sites.", hero_primary: "Get WhatsApp quote", hero_secondary: "Our services", hero_proof_1: "Van from 40 minutes", hero_proof_2: "Loaders on request", hero_proof_3: "Protective packing", status_today: "Today", status_from: "from", status_city: "Tbilisi + all Georgia",
    strip_1_title: "Careful handling", strip_1_text: "Furniture, appliances and personal items are treated gently.", strip_2_title: "Spacious van", strip_2_text: "Good for moving, delivery and cargo taxi orders.", strip_3_title: "Georgia routes", strip_3_text: "Tbilisi, Batumi, Kutaisi, Rustavi and other cities.", services_eyebrow: "What we move", services_title: "BoxMove services", services_text: "Book only a van, a van with loaders, junk removal, or a turnkey move with packing, disassembly and assembly.", service_1_title: "Furniture and appliance moving", service_1_text: "Sofas, wardrobes, fridges, washing machines and other bulky items.", service_2_title: "Construction material delivery", service_2_text: "Sand, cement, tiles, boards and materials delivered to your site.", service_3_title: "Cargo taxi in Tbilisi", service_3_text: "Fast van dispatch for boxes, purchases, equipment and goods.", service_4_title: "Office relocations", service_4_text: "Desks, chairs, documents, electronics and shop equipment.", service_5_title: "Loaders and packing", service_5_text: "Carrying by stairs, wrapping film, cardboard, corner protection and careful loading.", service_6_title: "Intercity transport", service_6_text: "Cargo delivery between Georgian cities with clear pricing and arrival time.", service_7_title: "Furniture assembly and disassembly", service_7_text: "We disassemble wardrobes, beds or tables before transport and assemble them at the new place.", service_8_title: "Junk removal", service_8_text: "We remove renovation waste, old furniture and unwanted items after a repair or move.", service_9_title: "Turnkey moving", service_9_text: "We bring boxes and wrap, pack items, disassemble furniture, move everything and assemble it at the new place.", service_cta: "Get quote",
    about_eyebrow: "Why BoxMove", about_title: "Moving should feel calm, not chaotic", about_text: "We clarify volume, floor, elevator, fragile items and route in advance. We arrive on time, secure the cargo inside the van and stay in touch until the job is complete.", about_stat_1: "average client rating", about_stat_2: "moves per season", about_stat_3: "average city dispatch", fleet_badge: "City and highway van", fleet_title: "Mercedes Sprinter / similar", fleet_text: "Clean cargo space, fastening straps, blankets and room for large furniture.",
    prices_eyebrow: "Clear quote", prices_title: "Popular formats", prices_text: "Every order is matched to the route, volume, floor, loaders, packing and waiting time. You can get a quick quote on WhatsApp.", price_1_label: "Cargo taxi", price_1_value: "City dispatch", price_1_text: "For quick transport around Tbilisi", price_1_item_1: "Van with driver", price_1_item_2: "Up to 1 hour of work", price_1_item_3: "Local pickup", price_2_label: "Move with loaders", price_2_value: "Team move", price_2_text: "For apartments, offices or stores", price_2_item_1: "Van + 2 loaders", price_2_item_2: "Loading and unloading", price_2_item_3: "Safe cargo fastening", price_3_label: "Intercity", price_3_value: "Georgia route", price_3_text: "Tbilisi - Batumi, Kutaisi, Rustavi and other cities", price_3_item_1: "Exact departure time", price_3_item_2: "Cargo photo before departure", price_3_item_3: "Contact on the road",
    quote_eyebrow: "Quick quote", quote_title: "Describe the move - we reply fast", quote_text: "The form opens a ready WhatsApp message. Add addresses, cargo type and number of loaders.", estimate_label: "Estimate:", estimate_note: "Exact price after details are confirmed", form_from: "From", form_to: "To", form_type: "Service type", form_helpers: "Loaders", form_comment: "What should be moved", form_from_placeholder: "Saburtalo, Tbilisi", form_to_placeholder: "Vake, Tbilisi", form_comment_placeholder: "Example: sofa, fridge, 12 boxes", form_type_taxi: "Cargo taxi", form_type_move: "Moving", form_type_turnkey: "Turnkey move", form_type_materials: "Construction materials", form_type_junk: "Junk removal", form_type_intercity: "Intercity", form_helpers_0: "No loaders", form_helpers_1: "1 loader", form_helpers_2: "2 loaders", form_helpers_3: "3+ loaders", form_submit: "Send to WhatsApp", reviews_eyebrow: "Reviews", reviews_title: "Clients value speed and careful work", review_1_text: "\"The team arrived on time, disassembled the wardrobe and carried everything carefully to the 5th floor. Price matched the agreement.\"", review_1_name: "Anna", review_1_meta: "Move from Vake to Saburtalo", review_2_text: "\"We needed tiles and cement delivered quickly to a site. The van arrived in an hour and they helped unload.\"", review_2_name: "Giorgi", review_2_meta: "Construction materials in Tbilisi", review_3_text: "\"We booked an office move in the evening. All boxes arrived safely and the equipment was secured.\"", review_3_name: "Maria", review_3_meta: "Office relocation",
    faq_eyebrow: "FAQ", faq_title: "Common questions", faq_1_q: "Can I book a van today?", faq_1_a: "Yes, if a slot is available. In Tbilisi we can often dispatch a van within 40-90 minutes.", faq_2_q: "Do you work without an elevator?", faq_2_a: "Yes. We clarify the floor and cargo volume in advance, so we can assign the right number of loaders and give a fair price.", faq_3_q: "Can you deliver to another city?", faq_3_a: "Yes, we transport cargo across Georgia. Price depends on distance, weight, volume and urgency.", faq_4_q: "Do you provide packing?", faq_4_a: "We can bring film, cardboard, tape and protective materials. Complex furniture can be disassembled and assembled.", contacts_eyebrow: "Contacts", contacts_title: "Message BoxMove - we will choose a van and time", contacts_text: "It is best to send photos of the items, addresses and preferred time. We will reply with price and available slot.", contacts_call: "Call", contacts_whatsapp: "WhatsApp", contacts_telegram: "Telegram", contacts_phone_label: "Phone", contacts_area_label: "Area", contacts_area: "Tbilisi and all Georgia", contacts_hours_label: "Hours", contacts_hours: "Daily 07:00-23:00, urgent orders 24/7", footer_text: "Moving, cargo transport and cargo taxi in Tbilisi and Georgia.", mobile_cta: "WhatsApp quote", whatsapp_message: "Hello, I want to get a BoxMove transport quote."
  },
  ka: {
    meta_title: "BoxMove - გადაზიდვები თბილისში და საქართველოში", meta_description: "BoxMove: ბინის და ოფისის გადატანა, სატვირთო ტაქსი, მტვირთავები და მიწოდება თბილისში და მთელ საქართველოში. სწრაფად, ფრთხილად, 24/7.", skip_link: "სერვისებზე გადასვლა", nav_services: "სერვისები", nav_about: "ჩვენ შესახებ", nav_prices: "ფორმატები", nav_reviews: "შეფასებები", nav_faq: "FAQ",
    hero_eyebrow: "გადაზიდვები თბილისში და მთელ საქართველოში", hero_title: "BoxMove ფრთხილად გადაიტანს ნივთებს, ავეჯს და დიდ ტვირთს", hero_text: "მოგაწვდით სუფთა ფურგონს, საჭიროების შემთხვევაში მტვირთავებს, შეფუთვას და მიწოდებას ზედმეტი სტრესის გარეშე. ვმუშაობთ ბინებთან, ოფისებთან, მაღაზიებთან და სამშენებლო ობიექტებთან.", hero_primary: "დათვლა WhatsApp-ში", hero_secondary: "ჩვენი სერვისები", hero_proof_1: "მანქანა 40 წუთიდან", hero_proof_2: "მტვირთავები მოთხოვნით", hero_proof_3: "დაცული შეფუთვა", status_today: "დღეს", status_from: "დან", status_city: "თბილისი + მთელი საქართველო",
    strip_1_title: "ფრთხილი მუშაობა", strip_1_text: "ავეჯს, ტექნიკას და პირად ნივთებს ფრთხილად ვეპყრობით.", strip_2_title: "ტევადი ფურგონი", strip_2_text: "გამოდგება გადატანისთვის, მიწოდებისთვის და სატვირთო ტაქსისთვის.", strip_3_title: "მარშრუტები საქართველოში", strip_3_text: "თბილისი, ბათუმი, ქუთაისი, რუსთავი და სხვა ქალაქები.", services_eyebrow: "რას გადავიტანთ", services_title: "BoxMove სერვისები", services_text: "შეგიძლიათ შეუკვეთოთ მხოლოდ მანქანა, მანქანა მტვირთავებით, ნარჩენების გატანა ან სრული გადატანა შეფუთვით, დაშლით და აწყობით.", service_1_title: "ავეჯის და ტექნიკის გადატანა", service_1_text: "დივნები, კარადები, მაცივრები, სარეცხი მანქანები და დიდი ნივთები.", service_2_title: "სამშენებლო მასალების მიწოდება", service_2_text: "ქვიშა, ცემენტი, ფილები, ფიცრები და მასალები ობიექტზე მიწოდებით.", service_3_title: "სატვირთო ტაქსი თბილისში", service_3_text: "სწრაფი მანქანა ყუთებისთვის, შენაძენებისთვის, ტექნიკისთვის და საქონლისთვის.", service_4_title: "ოფისის გადატანა", service_4_text: "მაგიდები, სკამები, დოკუმენტები, ტექნიკა და სავაჭრო ინვენტარი.", service_5_title: "მტვირთავები და შეფუთვა", service_5_text: "ატანა, ჩამოტანა, ფირი, მუყაო, კუთხეების დაცვა და ფრთხილი ჩატვირთვა.", service_6_title: "ქალაქებს შორის გადაზიდვა", service_6_text: "ტვირთის მიწოდება საქართველოს ქალაქებს შორის გასაგები ფასით და დროით.", service_7_title: "ავეჯის დაშლა და აწყობა", service_7_text: "გადატანამდე დავშლით კარადას, საწოლს ან მაგიდას და ახალ ადგილზე ავაწყობთ.", service_8_title: "ნარჩენების გატანა", service_8_text: "გავიტანთ სამშენებლო ნარჩენებს, ძველ ავეჯს და ზედმეტ ნივთებს რემონტის ან გადატანის შემდეგ.", service_9_title: "სრული გადატანა", service_9_text: "მოვიტანთ ყუთებს და ფირს, შევფუთავთ ნივთებს, დავშლით ავეჯს, გადავიტანთ და ახალ ადგილზე ავაწყობთ.", service_cta: "დათვლა",
    about_eyebrow: "რატომ BoxMove", about_title: "გადატანა მშვიდი უნდა იყოს და არა ქაოსური", about_text: "წინასწარ ვაზუსტებთ მოცულობას, სართულს, ლიფტს, მყიფე ნივთებს და მარშრუტს. მოვდივართ დროულად, ვამაგრებთ ტვირთს ფურგონში და კონტაქტზე ვართ დასრულებამდე.", about_stat_1: "კლიენტების საშუალო შეფასება", about_stat_2: "გადაზიდვა სეზონზე", about_stat_3: "საშუალო მიწოდება ქალაქში", fleet_badge: "ფურგონი ქალაქისთვის და გზისთვის", fleet_title: "Mercedes Sprinter / ანალოგი", fleet_text: "სუფთა საბარგო სივრცე, დამჭერი ღვედები, პლედები და ადგილი დიდი ავეჯისთვის.",
    prices_eyebrow: "გასაგები დათვლა", prices_title: "პოპულარული ფორმატები", prices_text: "ყოველ შეკვეთას ვარჩევთ მარშრუტის, მოცულობის, სართულის, მტვირთავების, შეფუთვის და ლოდინის მიხედვით. სწრაფი დათვლა შეგიძლიათ WhatsApp-ში.", price_1_label: "სატვირთო ტაქსი", price_1_value: "ქალაქში გამოძახება", price_1_text: "როცა ნივთების სწრაფად გადატანა გჭირდებათ თბილისში", price_1_item_1: "ფურგონი მძღოლით", price_1_item_2: "1 საათამდე მუშაობა", price_1_item_3: "ადგილობრივი მიწოდება", price_2_label: "გადატანა მტვირთავებით", price_2_value: "გადატანა გუნდით", price_2_text: "ბინისთვის, ოფისისთვის ან მაღაზიისთვის", price_2_item_1: "ფურგონი + 2 მტვირთავი", price_2_item_2: "ჩატვირთვა და გადმოტვირთვა", price_2_item_3: "ტვირთის უსაფრთხო დამაგრება", price_3_label: "ქალაქებს შორის", price_3_value: "მარშრუტი საქართველოში", price_3_text: "თბილისი - ბათუმი, ქუთაისი, რუსთავი და სხვა ქალაქები", price_3_item_1: "ზუსტი გასვლის დრო", price_3_item_2: "ტვირთის ფოტო გაგზავნამდე", price_3_item_3: "კავშირი გზაში",
    quote_eyebrow: "სწრაფი დათვლა", quote_title: "აღწერეთ გადაზიდვა - სწრაფად გიპასუხებთ", quote_text: "ფორმა ხსნის მზა WhatsApp შეტყობინებას. დაამატეთ მისამართები, ტვირთის ტიპი და მტვირთავების რაოდენობა.", estimate_label: "ორიენტირი:", estimate_note: "ზუსტი ფასი დეტალების დაზუსტების შემდეგ", form_from: "საიდან", form_to: "სად", form_type: "სერვისის ტიპი", form_helpers: "მტვირთავები", form_comment: "რა არის გადასატანი", form_from_placeholder: "საბურთალო, თბილისი", form_to_placeholder: "ვაკე, თბილისი", form_comment_placeholder: "მაგალითად: დივანი, მაცივარი, 12 ყუთი", form_type_taxi: "სატვირთო ტაქსი", form_type_move: "გადატანა", form_type_turnkey: "სრული გადატანა", form_type_materials: "სამშენებლო მასალები", form_type_junk: "ნარჩენების გატანა", form_type_intercity: "ქალაქებს შორის", form_helpers_0: "არ არის საჭირო", form_helpers_1: "1 მტვირთავი", form_helpers_2: "2 მტვირთავი", form_helpers_3: "3+ მტვირთავი", form_submit: "გაგზავნა WhatsApp-ში", reviews_eyebrow: "შეფასებები", reviews_title: "კლიენტები აფასებენ სისწრაფეს და სიფრთხილეს", review_1_text: "\"ბიჭები დროულად მოვიდნენ, კარადა დაშალეს და ყველაფერი ფრთხილად აიტანეს მე-5 სართულზე. ფასი შეთანხმების მიხედვით იყო.\"", review_1_name: "ანა", review_1_meta: "გადატანა ვაკე - საბურთალო", review_2_text: "\"საჭირო იყო ფილების და ცემენტის სწრაფად მიტანა ობიექტზე. მანქანა ერთ საათში მოვიდა და გადმოტვირთვაშიც დაგვეხმარნენ.\"", review_2_name: "გიორგი", review_2_meta: "სამშენებლო მასალები თბილისში", review_3_text: "\"ოფისის გადატანა საღამოს შევუკვეთეთ. ყველა ყუთი კარგად ჩავიდა, ტექნიკა დამაგრებული იყო.\"", review_3_name: "მარია", review_3_meta: "ოფისის გადატანა",
    faq_eyebrow: "FAQ", faq_title: "ხშირი კითხვები", faq_1_q: "შეიძლება მანქანის შეკვეთა დღეს?", faq_1_a: "დიახ, თუ თავისუფალი დრო არის. თბილისში ხშირად შეგვიძლია ფურგონის მიწოდება 40-90 წუთში.", faq_2_q: "ლიფტის გარეშე მუშაობთ?", faq_2_a: "დიახ. წინასწარ ვაზუსტებთ სართულს და ნივთების რაოდენობას, რომ სწორად შევარჩიოთ მტვირთავები და ფასი.", faq_3_q: "შეიძლება სხვა ქალაქში გადაზიდვა?", faq_3_a: "დიახ, ვმუშაობთ მთელ საქართველოში. ფასი დამოკიდებულია მანძილზე, წონაზე, მოცულობაზე და სისწრაფეზე.", faq_4_q: "შეფუთვა გაქვთ?", faq_4_a: "შეგვიძლია მოვიტანოთ ფირი, მუყაო, სკოჩი და დამცავი მასალები. რთული ავეჯის დაშლა და აწყობაც შესაძლებელია.", contacts_eyebrow: "კონტაქტი", contacts_title: "მოგვწერეთ BoxMove-ს - შევარჩევთ მანქანას და დროს", contacts_text: "საუკეთესოა ნივთების ფოტოები, მისამართები და სასურველი დრო გამოგვიგზავნოთ. სწრაფად გეტყვით ფასს და თავისუფალ დროს.", contacts_call: "დარეკვა", contacts_whatsapp: "WhatsApp", contacts_telegram: "Telegram", contacts_phone_label: "ტელეფონი", contacts_area_label: "ზონა", contacts_area: "თბილისი და მთელი საქართველო", contacts_hours_label: "დრო", contacts_hours: "ყოველდღე 07:00-23:00, სასწრაფო შეკვეთები 24/7", footer_text: "გადაზიდვები, ბინის გადატანა და სატვირთო ტაქსი თბილისში და საქართველოში.", mobile_cta: "WhatsApp დათვლა", whatsapp_message: "გამარჯობა, მინდა BoxMove გადაზიდვის დათვლა."
  }
};

const params = new URLSearchParams(window.location.search);
const state = { lang: params.get("lang") || localStorage.getItem("boxmove-lang") || "ru" };
if (!translations[state.lang]) state.lang = "ru";

const header = document.querySelector("[data-header]");
const nav = document.querySelector("[data-nav]");
const menuToggle = document.querySelector("[data-menu-toggle]");
const estimate = document.querySelector("[data-estimate]");
const serviceType = document.querySelector("[data-service-type]");
const helperCount = document.querySelector("[data-helper-count]");

function t(key) { return translations[state.lang][key] || translations.ru[key] || key; }

function setLanguage(lang) {
  if (!translations[lang]) return;
  state.lang = lang;
  localStorage.setItem("boxmove-lang", lang);
  document.documentElement.lang = lang;
  document.body.dataset.pageLang = lang;
  document.querySelectorAll("[data-i18n]").forEach(function (node) { node.textContent = t(node.dataset.i18n); });
  document.querySelectorAll("[data-i18n-html]").forEach(function (node) { node.innerHTML = t(node.dataset.i18nHtml); });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(function (node) { node.setAttribute("placeholder", t(node.dataset.i18nPlaceholder)); });
  document.title = t("meta_title");
  document.querySelector("meta[name='description']").setAttribute("content", t("meta_description"));
  document.querySelector("meta[property='og:title']").setAttribute("content", t("meta_title"));
  document.querySelector("meta[property='og:description']").setAttribute("content", t("meta_description"));
  document.querySelectorAll("[data-lang]").forEach(function (button) { button.classList.toggle("is-active", button.dataset.lang === lang); });
  document.querySelectorAll("[data-caption-key]").forEach(function (button) { button.dataset.caption = t(button.dataset.captionKey); });
  updateEstimate();
}

function updateHeader() { header.classList.toggle("is-scrolled", window.scrollY > 12); }
function closeMenu() { document.body.classList.remove("is-menu-open"); header.classList.remove("is-open"); nav.classList.remove("is-open"); menuToggle.setAttribute("aria-expanded", "false"); }
function updateEstimate() {
  if (!estimate || !serviceType || !helperCount) return;
  const typeBase = { taxi: 70, move: 70, turnkey: 140, materials: 70, junk: 90, intercity: 180 };
  const helpers = Number(helperCount.value || 0);
  const base = typeBase[serviceType.value] || 80;
  const total = base + helpers * 20;
  estimate.textContent = serviceType.value === "intercity" ? total + " ₾+" : total + " ₾";
}

document.querySelectorAll("[data-lang]").forEach(function (button) {
  button.addEventListener("click", function () {
    setLanguage(button.dataset.lang);
    const url = new URL(window.location.href);
    url.searchParams.set("lang", button.dataset.lang);
    window.history.replaceState({}, "", url);
  });
});

menuToggle.addEventListener("click", function () {
  const isOpen = nav.classList.toggle("is-open");
  document.body.classList.toggle("is-menu-open", isOpen);
  header.classList.toggle("is-open", isOpen);
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});
nav.querySelectorAll("a").forEach(function (link) { link.addEventListener("click", closeMenu); });
window.addEventListener("scroll", updateHeader, { passive: true });
updateHeader();

const observer = new IntersectionObserver(function (entries) {
  entries.forEach(function (entry) {
    if (entry.isIntersecting) {
      entry.target.classList.add("is-visible");
      observer.unobserve(entry.target);
    }
  });
}, { threshold: 0.16 });
document.querySelectorAll("[data-reveal]").forEach(function (node) { observer.observe(node); });
[serviceType, helperCount].forEach(function (node) { if (node) node.addEventListener("change", updateEstimate); });

document.querySelector("[data-quote-form]").addEventListener("submit", function (event) {
  event.preventDefault();
  const form = event.currentTarget;
  const data = new FormData(form);
  const lines = [
    t("whatsapp_message"),
    t("form_from") + ": " + (data.get("from") || "-"),
    t("form_to") + ": " + (data.get("to") || "-"),
    t("form_type") + ": " + form.querySelector("[name='type'] option:checked").textContent,
    t("form_helpers") + ": " + form.querySelector("[name='helpers'] option:checked").textContent,
    t("form_comment") + ": " + (data.get("comment") || "-")
  ];
  window.open("https://wa.me/" + PHONE + "?text=" + encodeURIComponent(lines.join("\n")), "_blank", "noopener");
});

setLanguage(state.lang);